# Configuration for CNN models comparison on STL10
experiment:
  name: "cnn_models_stl10"
  description: "Compare CNN models on STL10 dataset"
  
dataset:
  name: "stl10"
  num_epochs: 50
  eval_every: 100
  batch_size: 128
  
models:
  - model_class_name: "YatCNN"
    display_name: "YatCNN"
    rng_seed: 0
    kernel_viz_layer: "conv1"
    activation_viz_layer: "conv1"
  - model_class_name: "LinearCNN"
    display_name: "LinearCNN"
    rng_seed: 0
    kernel_viz_layer: "conv1"
    activation_viz_layer: "conv1"

training:
  learning_rate: 0.005
  optimizer: "adamw"
  
analysis:
  mode: "advanced"
  save_visualizations: true
  
output:
  save_dir: "experiments/cnn_stl10"
  save_models: true
  save_metrics: true
